Bump version to 1.10.1 (#12)
* Bump version to 1.10.1, change validation command name from upstream

* Update checkbox tests

* Deploy new firmware during snap refresh

* Move firmware version check to checkbox

* Firmware no longer managed by git lfs upstream

* Update README with test results

diff --git a/checkbox/bin/install-full-deps b/checkbox/bin/install-full-deps
--- a/checkbox/bin/install-full-deps
+++ b/checkbox/bin/install-full-deps
@@ -6,9 +6,9 @@ if [ "${optional_arg}" = "--install_from_store" ]; then
   sudo snap install --beta intel-npu-driver
 fi
 
-if ! command -v intel-npu-driver.vpu-umd-test 2>&1 >/dev/null
+if ! command -v intel-npu-driver.npu-umd-test 2>&1 >/dev/null
 then
-  echo "Error: intel-npu-driver.vpu-umd-test could not be found!"
+  echo "Error: intel-npu-driver.npu-umd-test could not be found!"
   echo "Either install the intel-npu-driver snap locally or from the store (using --install_from_store)"
   exit 1
 fi
@@ -16,7 +16,7 @@ fi
 # $HOME/snap/intel-npu-driver/current is created the first time
 # an app from the snap is run. We simply pass the -l (list) option
 # to generate this directory for subsequent steps.
-intel-npu-driver.vpu-umd-test -l 2>&1 >/dev/null
+intel-npu-driver.npu-umd-test -l 2>&1 >/dev/null
 
 # Exit if any of the steps below fail
 set -e
@@ -26,4 +26,4 @@ cd $HOME/snap/intel-npu-driver/current
 mkdir -p models/add_abc
 curl -s -o models/add_abc/add_abc.xml https://raw.githubusercontent.com/openvinotoolkit/openvino/master/src/core/tests/models/ir/add_abc.xml
 touch models/add_abc/add_abc.bin
-curl -s -o basic.yaml https://raw.githubusercontent.com/intel/linux-npu-driver/v1.6.0/validation/umd-test/configs/basic.yaml
+curl -s -o basic.yaml https://raw.githubusercontent.com/intel/linux-npu-driver/v1.10.1/validation/umd-test/configs/basic.yaml
